# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"c\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"f\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\t\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusB\x0b\n\titem_type\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t*M\n\x05Genre\x12\x11\n\rUNKNOWN_GENRE\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\x13\n\x0fSCIENCE_FICTION\x10\x03*6\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\t\n\x05TAKEN\x10\x02\x32]\n\x10InventoryService\x12%\n\nCreateBook\x12\x05.Book\x1a\x0e.StringMessage\"\x00\x12\"\n\x07GetBook\x12\x0e.StringMessage\x1a\x05.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=256
  _GENRE._serialized_end=333
  _STATUS._serialized_start=335
  _STATUS._serialized_end=389
  _BOOK._serialized_start=19
  _BOOK._serialized_end=118
  _INVENTORYITEM._serialized_start=120
  _INVENTORYITEM._serialized_end=222
  _STRINGMESSAGE._serialized_start=224
  _STRINGMESSAGE._serialized_end=254
  _INVENTORYSERVICE._serialized_start=391
  _INVENTORYSERVICE._serialized_end=484
# @@protoc_insertion_point(module_scope)
